image:
  name: "us.gcr.io/tacit-196502/go-build:latest"

build:
  script:
    - docker login -u _json_key -p "$DOCKER_PASSWORD" https://us.gcr.io
    - mkdir -p /root/src/tacit-api
    - cp -R . /root/src/tacit-api
    - cd /root/src/tacit-api
    - dep ensure
    - go build
    - docker build -t us.gcr.io/tacit-196502/myapi:0.0.3 .
    - docker push us.gcr.io/tacit-196502/myapi:0.0.3
    - gcloud auth activate-service-account --key-file="$DOCKER_PASSWORD" 
    - kubectl apply -f ./kube/deployment.yaml
    
#package:
#  script:
#    - docker ps
