before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

build:
  script:
    - mkdir -p /go/src/tacit-api
    - cp -R . /go/src
    - cd /go/src
    - dep ensure
    - go build
