image:
  name: "us.gcr.io/tacit-196502/go-build:master"
  
stages: 
  - testing
  - build
  - deploy

testing:
  stage: testing
  script:
    - mkdir -p /root/src/tacit-api
    - cp -R . /root/src/tacit-api
    - cd /root/src/tacit-api
    - dep ensure
    - chmod +x ./scripts/runTest.sh
    - ./scripts/runTest.sh
    - go test

build:
  stage: build
  script:
    - docker login -u _json_key -p "$DOCKER_PASSWORD" https://us.gcr.io
    - mkdir -p /root/src/tacit-api
    - cp -R . /root/src/tacit-api
    - cd /root/src/tacit-api
    - dep ensure
    - CGO_ENABLED=0 go build
    - docker build -t us.gcr.io/tacit-196502/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - export DOCKER_FRIENDLY_REF_NAME=$(echo $CI_COMMIT_REF_NAME | sed "s/\//_/g")
    - docker tag us.gcr.io/tacit-196502/$CI_PROJECT_NAME:$CI_COMMIT_SHA us.gcr.io/tacit-196502/$CI_PROJECT_NAME:$DOCKER_FRIENDLY_REF_NAME
    - docker push us.gcr.io/tacit-196502/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push us.gcr.io/tacit-196502/$CI_PROJECT_NAME:$DOCKER_FRIENDLY_REF_NAME
    
.deploy_template: &deploy_dev
  stage: deploy
  script:
    - export jkey=$(mktemp)
    - echo "$DOCKER_PASSWORD" > $jkey
    - gcloud auth activate-service-account --key-file=$jkey
    - gcloud container clusters get-credentials tacit-dev --zone us-central1-a --project tacit-196502
    - export DOCKER_FRIENDLY_REF_NAME=$(echo $CI_COMMIT_REF_NAME | sed "s/\//_/g")
    - sed "s/{{TAG}}/$DOCKER_FRIENDLY_REF_NAME/g" kube/deployment.yaml > kube/finalDeployment.yaml
    - kubectl apply -f ./kube/finalDeployment.yaml
    - rm $jkey
    
deploy_feature: 
    <<: *deploy_dev
    when: manual
    except: 
        - master
        - develop

deploy_develop_master: 
    <<: *deploy_dev
    only:
        - master
        - develop
    

#package:
#  script:
#    - docker ps
 
