iamge:
  - "base/archlinux"
  
before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

build:
  script:
    - mkdir -p /go/src/tacit-api
    - cp -R . /go/src/tacit-api
    - cd /go/src/tacit-api
    - pwd
    - dep ensure
    - go build
    
package:
  script:
    - docker ps
