image:
  name: "us.gcr.io/tacit-196502/go-build:latest"

build:
  script:
    - docker login -u _json_key -p "$DOCKER_PASSWORD" https://us.gcr.io
    - mkdir -p /root/src/tacit-api
    - cp -R . /root/src/tacit-api
    - cd /root/src/tacit-api
    - dep ensure
    - go build
    - echo $CI_PROJECT_ID
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_PATH_SLUG
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_REF_NAME
    - docker build -t us.gcr.io/tacit-196502/myapi:0.0.3 .
    - docker push us.gcr.io/tacit-196502/myapi:0.0.3
    
deploy:
  script:
    - export jkey=$(mktemp)
    - echo $jkey
    - echo "$DOCKER_PASSWORD" > $jkey
    - gcloud auth activate-service-account --key-file=$jkey
    - gcloud container clusters get-credentials tacit-dev --zone us-central1-a --project tacit-196502
    - kubectl apply -f ./kube/deployment.yaml
    - rm $jkey
    
#package:
#  script:
#    - docker ps
 