before_script:
  - ls -la
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep version

build:
  script:
    - echo $GOPATH
    - pwd
    - ls /go
    - cp -R . /go/src
    - cd /go/src
    - dep ensure
    - go build
