apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-deployment
spec:
  selector: 
    matchLabels:
      app: api
  replicas: 1
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: myapi
        image: myapi:0.0.1
        ports:
        - containerPort: 8080